arm64: arch_timer: Initialize val in arch_timer_reg_read_cp15
../arch/arm64/include/asm/arch_timer.h:75:13: error: variable 'val' is
used uninitialized whenever 'if' condition is false
[-Werror,-Wsometimes-uninitialized]

This is a false positive.

Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>
(cherry picked from commit 589fd715861866dfb030ff5ac703fc542432d852)
Signed-off-by: fadlyas07 <fadlyardhians@gmail.com>